/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zolera.chat.ui;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import zolera.chat.client.ClientModel;
import zolera.chat.client.TerminateClientException;
import zolera.chat.infrastructure.ServerConfiguration;

/**
 *
 * @author ortiz
 */
public class LoginView extends javax.swing.JFrame {
    
    private ServerConfiguration config;
    private GUIView controller;
    private ClientModel client;
    
    private String errorMessage;
    
    /**
     * Creates new form LoginFrame
     * @param control
     */
    public LoginView(GUIView control) {
        if (control == null)
            throw new IllegalArgumentException("Expecting a controller");
        
        config     = ServerConfiguration.getGlobal();
        controller = control;
        client     = controller.getClient();
        
        errorMessage = null;
        
        initComponents();
    }
    
    
    
    private String getErrorMessage() {
        if (errorMessage != null)
            return errorMessage;
        
        Exception ex = controller.getPendingException();
        if (ex == null)
            errorMessage = "";
        else {
            controller.setPendingException(null);
            errorMessage = "Error: " + ex.getMessage();
        }
        
        return errorMessage;
    }
    
    private ComboBoxModel getServerAddressesModel() {
        String[] addresses = new String[config.getRegistryAddressesListLength()];
        
        for (int addr = 0; addr < config.getRegistryAddressesListLength(); addr++)
            addresses[addr] = config.getRegistryAddress(addr);
        
        return new DefaultComboBoxModel(addresses);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblServer = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        cmbServer = new javax.swing.JComboBox();
        btnJoin = new javax.swing.JButton();
        pnlErrorExt = new javax.swing.JPanel();
        lblErrorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 160));
        setResizable(false);

        lblUsername.setLabelFor(txfUsername);
        lblUsername.setText("Username");

        lblServer.setLabelFor(cmbServer);
        lblServer.setText("Server");

        cmbServer.setModel(getServerAddressesModel());

        btnJoin.setText("Join");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        pnlErrorExt.setPreferredSize(new java.awt.Dimension(97, 50));
        pnlErrorExt.setVisible(!getErrorMessage().equals(""));

        lblErrorMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMsg.setText(getErrorMessage());

        javax.swing.GroupLayout pnlErrorExtLayout = new javax.swing.GroupLayout(pnlErrorExt);
        pnlErrorExt.setLayout(pnlErrorExtLayout);
        pnlErrorExtLayout.setHorizontalGroup(
            pnlErrorExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblErrorMsg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlErrorExtLayout.setVerticalGroup(
            pnlErrorExtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlErrorExtLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblServer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbServer, 0, 209, Short.MAX_VALUE)
                                    .addComponent(txfUsername)))
                            .addComponent(pnlErrorExt, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServer)
                    .addComponent(cmbServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJoin)
                .addGap(0, 0, 0)
                .addComponent(pnlErrorExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        try {
            client.connect(cmbServer.getSelectedIndex());
            client.join(roomname, username, procMsg, null);
            controller.setUsername(txfUsername.getText());
            controller.setRoomname(config.getDefaultRoomname());
            controller.setServerId(cmbServer.getSelectedIndex());
            controller.switchView(GUIView.CHAT);
        }
        catch (TerminateClientException tce) {
            controller.terminateClient(tce);
        }
    }//GEN-LAST:event_btnJoinActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJoin;
    private javax.swing.JComboBox cmbServer;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlErrorExt;
    private javax.swing.JTextField txfUsername;
    // End of variables declaration//GEN-END:variables
}
